#!/usr/bin/env bash
set -euo pipefail

: "${DEPLOY_SSH_KEY:?Missing secret HAPI_DEPLOY_SSH_KEY}"
: "${TS_OAUTH_CLIENT_ID:?Missing secret TS_OAUTH_CLIENT_ID}"
: "${TS_AUDIENCE:?Missing secret TS_AUDIENCE}"
: "${HAPI_DEPLOY_HOST:?Missing repository variable HAPI_DEPLOY_HOST}"
: "${GITHUB_ENV:?GITHUB_ENV is required}"

HAPI_DEPLOY_USER="${HAPI_DEPLOY_USER:-enoch}"
HAPI_DEPLOY_KEEP_RELEASES="${HAPI_DEPLOY_KEEP_RELEASES:-5}"
HAPI_DEPLOY_ROOT="${HAPI_DEPLOY_ROOT:-/home/${HAPI_DEPLOY_USER}/.local/share/hapi-deploy}"
HAPI_DEPLOY_REPO_PATH="${HAPI_DEPLOY_REPO_PATH:-/home/${HAPI_DEPLOY_USER}/projects/hapi}"

{
    echo "HAPI_DEPLOY_USER=$HAPI_DEPLOY_USER"
    echo "HAPI_DEPLOY_KEEP_RELEASES=$HAPI_DEPLOY_KEEP_RELEASES"
    echo "HAPI_DEPLOY_ROOT=$HAPI_DEPLOY_ROOT"
    echo "HAPI_DEPLOY_REPO_PATH=$HAPI_DEPLOY_REPO_PATH"
    echo "DEPLOY_TARGET=${HAPI_DEPLOY_USER}@${HAPI_DEPLOY_HOST}"
    echo "HAPI_DEPLOY_SOURCE_PATH=${HAPI_DEPLOY_ROOT}/workspace"
} >> "$GITHUB_ENV"
